# -------------------------------------------------------------------------------------
# Front Matter Configuration | Front Matter
# See: https://gohugo.io/configuration/front-matter/
# -------------------------------------------------------------------------------------

lastmod = [
  "lastmod",
  ":git",
  ":fileModTime",
  ":default"
]
