# -------------------------------------------------------------------------------------
# Hugo Configuration | Hugo
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

# website title
title = "S. Ravivarman"

# Hostname (and path) to the root
baseURL = "https://sravivarman.github.io/website2/"

# theme
# theme = ["FixIt", "shortcode-rewards"]

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
hasCJKLanguage = false
# Timezone Local
timeZone = "Asia/Kolkata"

# copyright description used only for seo schema
copyright = ""

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
# the main sections of a site
mainSections = [
  "contributing",
  "documentation",
  "ecosystem",
  "guides",
  "references",
  "guides",
]

# the editor to use when creating new content
newContentEditor = "code"

# whether to capitalize automatic list titles
titleCaseStyle = "ap"
capitalizeListTitles = false

# ignore some build errors
ignoreLogs = [
  "error-get-remote-json",
  "error-get-gh-repo",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken",
  "err-youtube-remote",
  "warning-dev-version",
  "shortcode-x-getremote",
]
