# -------------------------------------------------------------------------------------
# Languages Configuration |
# See: https://gohugo.io/configuration/languages/
# -------------------------------------------------------------------------------------

weight = 1
# language directory
contentDir = "content/en"
# language code
languageCode = "en"
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# copyright description used only for seo schema
copyright = "This work is licensed under CC BY-NC-SA-4.0."
