# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

# -----------------------------
# Home
# -----------------------------
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[main.params]
icon = "fa-solid fa-house"


# -----------------------------
# Teaching
# -----------------------------
[[main]]
identifier = "teaching"
name = "Teaching"
url = "/teaching/"
weight = 2

[main.params]
icon = "fa-solid fa-chalkboard-teacher"


# Teaching → Courses
[[main]]
identifier = "courses"
parent = "teaching"
name = "Courses"
url = "/courses/"
weight = 1

[main.params]
icon = "fa-solid fa-book-open"


# -----------------------------
# Blog
# -----------------------------
[[main]]
identifier = "blog"
name = "Blog"
url = "/archives/"
weight = 3

[main.params]
icon = "fa-solid fa-feather"


# Blog → Archives
[[main]]
identifier = "archives"
parent = "blog"
name = "Archives"
url = "/archives/"
weight = 1

[main.params]
icon = "fa-solid fa-archive"


# Blog → Categories
[[main]]
identifier = "categories"
parent = "blog"
name = "Categories"
url = "/categories/"
weight = 2

[main.params]
icon = "fa-solid fa-folder-tree"


# Blog → Collections
[[main]]
identifier = "collections"
parent = "blog"
name = "Collections"
url = "/collections/"
weight = 3

[main.params]
icon = "fa-solid fa-layer-group"


# Blog → Tags
[[main]]
identifier = "tags"
parent = "blog"
name = "Tags"
url = "/tags/"
weight = 4

[main.params]
icon = "fa-solid fa-tags"


# -----------------------------
# Projects
# -----------------------------
[[main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 4

[main.params]
icon = "fa-solid fa-diagram-project"


# -----------------------------
# Research
# -----------------------------
[[main]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 5

[main.params]
icon = "fa-solid fa-flask"


# -----------------------------
# About
# -----------------------------
[[main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 90

[main.params]
icon = "fa-solid fa-user"


# -----------------------------
# Contact
# -----------------------------
[[main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 100

[main.params]
icon = "fa-solid fa-envelope"






[[main]]
identifier = "releases"
parent = "documentation"
name = "Releases"
post = '<i class="fa-solid fa-external-link-alt fa-fw fa-xs text-secondary"></i>'
url = "https://github.com/hugo-fixit/FixIt/releases"
weight = 5

[main.params]
icon = "fa-solid fa-code-branch"

[[main]]
identifier = "archives"
parent = "documentation"
name = "Archives"
url = "archives/"
weight = 20

[main.params]
icon = "fa-solid fa-archive"
divided = true

[[main]]
identifier = "categories"
parent = "documentation"
name = "Categories"
url = "categories/"
weight = 21

[main.params]
icon = "fa-solid fa-folder-tree"

[[main]]
identifier = "collections"
parent = "documentation"
name = "Collections"
url = "collections/"
weight = 22

[main.params]
icon = "fa-solid fa-layer-group"

[[main]]
identifier = "tags"
parent = "documentation"
name = "Tags"
url = "tags/"
weight = 23

[main.params]
icon = "fa-solid fa-tags"

[[main]]
identifier = "showcase"
name = "Showcase"
url = "showcase/"
weight = 31

[main.params]
icon = "fa-solid fa-blog"

[[main]]
identifier = "community"
name = "Community"
url = "community/"
weight = 40

[main.params]
icon = "fa-regular fa-comments"

[[main]]
identifier = "github"
pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
url = "https://github.com/hugo-fixit/FixIt"
title = "GitHub"
weight = 100

[main.params]
class = "text-center"
type = "mobile"
